version: 0.2

env:
  variables:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url
    IMAGE_NAME: "eliyasankark/mypyapp"

phases:
  install:
    commands:
      - echo "Skipping Docker installation since it's already installed..."

  pre_build:
    commands:
      - echo "Checking environment variables..."
      - echo "DOCKER_REGISTRY_URL is ${DOCKER_REGISTRY_URL}"
      - echo "DOCKER_REGISTRY_USERNAME is ${DOCKER_REGISTRY_USERNAME}"
      - echo "DOCKER_REGISTRY_PASSWORD is set"

  build:
    commands:
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/pyaws-app:latest" .
      - docker push "docker.io/eliyasankark/pyaws-app:latest"
post_build:
  commands:
   # - echo Pushing the Docker image to Docker Hub...
   # - docker tag my-image:latest my-dockerhub-username/my-repo:latest
   # - docker push my-dockerhub-username/my-repo:latest




artifacts:
  files:
    - '**/*'
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
    - '/root/.cache/pip/**/*'
